### ISSUE TITLE
PayloadType com.apple.security.pkcs1 is not supported

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence-windows-agent#13]
After merge of https://github.com/inverse-inc/packetfence/pull/5970, a customer has reported an issue on Windows provisioner.

When running Windows provisioner for EAP-TLS, he got this message:

`Unexpected PayloadType com.apple.security.pkcs1 please contact your local support.`

### Steps to reproduce

Issue has been introduced by [following change](https://github.com/inverse-inc/packetfence/pull/5970/commits/8623dc222f3ef2d109b3d4609c6d2170db662228#diff-404a8565b8076a66809b4873ab95ff33af137c9247a4c163622b681e4b439af2).

### Expected results
Support com.apple.security.pkcs1 PayloadType or display a more explicit error.

**Comment by nqb** [comment]
According to [current code](https://github.com/inverse-inc/packetfence-windows-agent/blob/54112a26ff6faea40e59dc84ae0bbc89384a2dfb/parse.go#L228-L234), it looks like we exit if we find an unexpected PayloadType.

**Comment by JeGoi** [comment]
Also fixed there: https://github.com/inverse-inc/packetfence/commit/87875429d19924c2a93d0fca4896951cd9d9fdea
