### ISSUE TITLE
Can`t download profile.xml form  PROFILE_URL = "http://wireless-profiles.packetfence.org/profile.xml"

### ISSUE THREAD

**Issue by gimmymatt** [inverse-inc/packetfence-windows-agent#14]
Can`t download profile.xml form  PROFILE_URL = "http://wireless-profiles.packetfence.org/profile.xml"

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.
