### ISSUE TITLE
Agent with EAP-TLS PKI provider : certificates not imported

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence-windows-agent#9]
As said in #8, when using `packetfence-windows-agent` to provision a Windows machine with a windows provisioner that uses a PKI provider for EAP-TLS, RADIUS server and user certificates are not imported.

Steps to reproduce : 

- Configure a PKI provider using PacketFence-PKI (see doc)
  - Common name attribute : MAC Address
- Configure a Windows provisioner : 
  -  SSID : your secure SSID
  - EAP type : EAP-TLS
  - Security type : name of your PKI provider
- Connect to insecure SSID and launch `packetfence-windows-agent` with admin rights

Actual results : 
- No RADIUS server certificate imported : agent said that all was right
- No User certificate imported : agent said that all was right
- Network profile added with `Do not prompt user to authorize new servers or trusted certification` option checked. With Python, this option was unchecked.

Expected results : 
- RADIUS certificate inported, if not print an error message
- User certificate imported, if not print an error message
- Uncheck `Do not prompt user to authorize new servers or trusted certification` in network profile added

**Comment by extrafu** [comment]
Let's bundle the Python agent and we'll review this with @Zouelie later.

**Comment by extrafu** [comment]
@nqb @atran-inverse @Zouelie I'll take care of this issue this week.

**Comment by extrafu** [comment]
I cannot reproduce this issue on Windows 10 and 7.

**Comment by nqb** [comment]
I did new tests with Golang agent, PF 10.2 and Windows 10: 

Certificates are correctly imported in scenario described. However, [current XML file](https://github.com/inverse-inc/packetfence/blob/94ea444e1bf4943b5f5d6ba18225512542aa9e32/html/captive-portal/templates/wireless-profile-tls.xml) to install certificates doesn't permit to install **server certificate**, only client and CA certificates which make sense for me: you only want to import CA certificate to trust RADIUS certificate.

Also see: https://github.com/inverse-inc/packetfence/issues/3432
